CREATE TABLE `TIPO_USUARIO` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `nombre` varchar(30) NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `FACULTAD` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `nombre_facultad` varchar(200) NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `DEPARTAMENTO_UNIDAD` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `nombre_departamento` varchar(200) NOT NULL,
  `facultad_id` int,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `CARRERA` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `nombre_carrera` varchar(200) NOT NULL,
  `grado` varchar(200) NOT NULL,
  `facultad_id` int NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `USUARIO` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `foto` varchar(200),
  `correo` varchar(100) NOT NULL,
  `contrasena` varchar(255) NOT NULL,
  `tipo_usuario_id` int NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `DIRECTOR_CARRERA` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `usuario_id` int NOT NULL,
  `carrera_id` int NOT NULL,
  `empleado_id` int NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `EXTERNO` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) NOT NULL,
  `apellido` varchar(100) NOT NULL,
  `correo` varchar(100) NOT NULL,
  `descripcion` text NOT NULL,
  `rol_externo` bool NOT NULL,
  `departamento_unidad_id` int NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `TIPO_EMPLEADO` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `nombre_tipo_empleado` varchar(20) NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `CARGO` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `nombre_cargo` varchar(100) NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `EMPLEADO` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `codigo_empleado` varchar(10) NOT NULL,
  `nombre` varchar(100) NOT NULL,
  `apellido` varchar(100) NOT NULL,
  `tipo_empleado_id` int NOT NULL,
  `cargo_id` int NOT NULL,
  `departamento_unidad_id` int NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `GRUPO_TRABAJO` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `anio_inicio` int NOT NULL,
  `ciclo_inicio` int NOT NULL,
  `tema` text NOT NULL,
  `prorroga` bool NOT NULL,
  `asesor_interno_id` int,
  `lector_interno_id` int,
  `asesor_externo_id` int,
  `lector_externo_id` int,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `ESTUDIANTE` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) NOT NULL,
  `apellido` varchar(100) NOT NULL,
  `carnet` char(10) NOT NULL,
  `carrera_id` int NOT NULL,
  `usuario_id` int NOT NULL,
  `grupo_trabajo_id` int,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `SECCION_RESUMEN` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `contenido` text NOT NULL,
  `grupo_trabajo_id` int NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `SECCION_CAPITULO` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `nombre_capitulo` varchar(200) NOT NULL,
  `orden_capitulo` int NOT NULL,
  `grupo_trabajo_id` int NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `CONTENIDO_SECCION_CAPITULO` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `tema` varchar(255),
  `contenido` text NOT NULL,
  `orden_contenido` int NOT NULL,
  `seccion_capitulos_id` int NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `SUBCONTENIDO_SECCION_CAPITULO` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `subtema` text NOT NULL,
  `contenido` text NOT NULL,
  `orden_subcontenido` int NOT NULL,
  `contenido_seccion_capitulo_id` int NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `SECCION_GLOSARIO` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `opcional` bool NOT NULL,
  `contenido` text NOT NULL,
  `grupo_trabajo_id` int NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `TIPO_ABREVIATURA` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `nombre_tipo_abreviatura` varchar(20) NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `SECCION_ABREVIATURA_NOMENCLATURA_SIGLA` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `contenido` text NOT NULL,
  `tipo_abreviatura_id` int NOT NULL,
  `grupo_trabajo_id` int NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `SECCION_AGRADECIMIENTO` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `opcional` bool NOT NULL,
  `autor` varchar(100),
  `contenido` text NOT NULL,
  `estudiante_id` int NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `SECCION_DEDICATORIA` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `opcional` bool NOT NULL,
  `autor` varchar(100) NOT NULL,
  `contenido` text NOT NULL,
  `estudiante_id` int NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `SECCION_REFERENCIA` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `contenido` text NOT NULL,
  `grupo_trabajo_id` int NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `BITACORA_SECCION` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `nombre_seccion` varchar(30) NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `BITACORA_MODIFICACION` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `nombre_modificacion` varchar(20) NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `BITACORA` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `descripcion` text NOT NULL,
  `fecha_modificacion` datetime NOT NULL,
  `estudiante_id` int NOT NULL,
  `bitacora_seccion_id` int NOT NULL,
  `bitacora_modificacion_id` int NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

CREATE TABLE `CONFIGURACION_SISTEMA` (
  `id` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `fecha_entrega` varchar(20) NOT NULL,
  `fecha_prorroga` varchar(20) NOT NULL,
  `numero_integrantes` int NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDb;

ALTER TABLE `DEPARTAMENTO_UNIDAD` ADD FOREIGN KEY (`facultad_id`) REFERENCES `FACULTAD` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `CARRERA` ADD FOREIGN KEY (`facultad_id`) REFERENCES `FACULTAD` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `USUARIO` ADD FOREIGN KEY (`tipo_usuario_id`) REFERENCES `TIPO_USUARIO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `DIRECTOR_CARRERA` ADD FOREIGN KEY (`carrera_id`) REFERENCES `CARRERA` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `DIRECTOR_CARRERA` ADD FOREIGN KEY (`usuario_id`) REFERENCES `USUARIO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `DIRECTOR_CARRERA` ADD FOREIGN KEY (`empleado_id`) REFERENCES `EMPLEADO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `EXTERNO` ADD FOREIGN KEY (`departamento_unidad_id`) REFERENCES `DEPARTAMENTO_UNIDAD` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `EMPLEADO` ADD FOREIGN KEY (`tipo_empleado_id`) REFERENCES `TIPO_EMPLEADO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `EMPLEADO` ADD FOREIGN KEY (`cargo_id`) REFERENCES `CARGO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `EMPLEADO` ADD FOREIGN KEY (`departamento_unidad_id`) REFERENCES `DEPARTAMENTO_UNIDAD` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `GRUPO_TRABAJO` ADD FOREIGN KEY (`asesor_interno_id`) REFERENCES `EMPLEADO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `GRUPO_TRABAJO` ADD FOREIGN KEY (`lector_interno_id`) REFERENCES `EMPLEADO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `GRUPO_TRABAJO` ADD FOREIGN KEY (`asesor_externo_id`) REFERENCES `EXTERNO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `GRUPO_TRABAJO` ADD FOREIGN KEY (`lector_externo_id`) REFERENCES `EXTERNO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `ESTUDIANTE` ADD FOREIGN KEY (`carrera_id`) REFERENCES `CARRERA` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `ESTUDIANTE` ADD FOREIGN KEY (`usuario_id`) REFERENCES `USUARIO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `ESTUDIANTE` ADD FOREIGN KEY (`grupo_trabajo_id`) REFERENCES `GRUPO_TRABAJO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SECCION_RESUMEN` ADD FOREIGN KEY (`grupo_trabajo_id`) REFERENCES `GRUPO_TRABAJO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SECCION_CAPITULO` ADD FOREIGN KEY (`grupo_trabajo_id`) REFERENCES `GRUPO_TRABAJO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `CONTENIDO_SECCION_CAPITULO` ADD FOREIGN KEY (`seccion_capitulos_id`) REFERENCES `SECCION_CAPITULO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SUBCONTENIDO_SECCION_CAPITULO` ADD FOREIGN KEY (`contenido_seccion_capitulo_id`) REFERENCES `CONTENIDO_SECCION_CAPITULO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SECCION_GLOSARIO` ADD FOREIGN KEY (`grupo_trabajo_id`) REFERENCES `GRUPO_TRABAJO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SECCION_ABREVIATURA_NOMENCLATURA_SIGLA` ADD FOREIGN KEY (`tipo_abreviatura_id`) REFERENCES `TIPO_ABREVIATURA` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SECCION_ABREVIATURA_NOMENCLATURA_SIGLA` ADD FOREIGN KEY (`grupo_trabajo_id`) REFERENCES `GRUPO_TRABAJO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SECCION_AGRADECIMIENTO` ADD FOREIGN KEY (`estudiante_id`) REFERENCES `ESTUDIANTE` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SECCION_DEDICATORIA` ADD FOREIGN KEY (`estudiante_id`) REFERENCES `ESTUDIANTE` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SECCION_REFERENCIA` ADD FOREIGN KEY (`grupo_trabajo_id`) REFERENCES `GRUPO_TRABAJO` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `BITACORA` ADD FOREIGN KEY (`estudiante_id`) REFERENCES `ESTUDIANTE` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `BITACORA` ADD FOREIGN KEY (`bitacora_seccion_id`) REFERENCES `BITACORA_SECCION` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `BITACORA` ADD FOREIGN KEY (`bitacora_modificacion_id`) REFERENCES `BITACORA_MODIFICACION` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
